In [80]:
from infomax_index import get_index_list, get_index_pdf
lst = get_index_list()
bbig = lst[lst.kr_name.str.contains("KRX BBIG 지수")]
bbig_code = bbig.code.values[0]
bbig_pdf = get_index_pdf(bbig_code)

print(bbig)

    index_type    code      kr_name         en_name
366        KRX  XGT01P  KRX BBIG 지수  KRX BBIG Index

In [74]:
from infomax_equity import get_equity_daily, get_equity_base
from infomax_index import get_index_daily, get_index_base_info

codes = ",".join(bbig_pdf.code.tolist())
index_code = bbig.code.iloc[0]

dt0 = "20240423"
dt1 = "20240424"
dt2 = "20240425"

index_dt1 = get_index_base_info(index_code, dt1)
index_dt2 = get_index_base_info(index_code, dt2)
index_hist = get_index_daily(index_code, "20240423", dt2)

equity_dt0 = get_equity_base(codes, dt0)
equity_dt1 = get_equity_base(codes, dt1)
equity_dt2 = get_equity_base(codes, dt2)

In [71]:
def get_index_change_rate(pdf_df):
    return pdf_df['change_rate'].sum()/len(pdf_df)


print(get_index_change_rate(equity_dt0))
print(get_index_change_rate(equity_dt1))
print(get_index_change_rate(equity_dt2))

-2.1024999999999996
2.1875
-2.936666666666667

In [75]:
def get_market_cap(df):
    df['normalized_shares'] = df['listed_shares'] / 100000000.
    df['market_cap'] = df['normalized_shares'] * df['close_price']
    total_cap = df['market_cap'].sum()
    df['market_cap_ratio'] = df['market_cap'] / total_cap

    return df

res0 = get_market_cap(equity_dt0)
res1 = get_market_cap(equity_dt1)
res2 = get_market_cap(equity_dt2)

In [76]:
res0[['kr_name', 'market_cap_ratio']]

     kr_name  market_cap_ratio
0     포스코퓨처엠          0.068943
1      삼성SDI          0.090577
2      NAVER          0.094663
3        카카오          0.068447
4      엔씨소프트          0.012114
5       셀트리온          0.126813
6   삼성바이오로직스          0.182204
7        넷마블          0.015439
8       크래프톤          0.037253
9     SK바이오팜          0.021290
10  LG에너지솔루션          0.280206
11       디어유          0.002051

In [61]:
(res1-res0)/res0

0.023797916774867717

In [58]:
index_hist

,date,index_type,code,kr_name,open_price,high_price,low_price,close_price,change,change_rate,...,advanced_volume,top_gain_volume,declined_volume,top_lose_volume,equal_volume,advanced_value,top_gain_value,declined_value,top_lose_value,equal_value
0,20240425,KRX,XGT01P,KRX BBIG 지수,1666.25,1666.25,1646.94,1646.94,-40.15,-2.38,...,178,0,3503,0,0,9441,0,648570,0,0
1,20240424,KRX,XGT01P,KRX BBIG 지수,1683.95,1694.24,1678.80,1687.09,30.75,1.86,...,3446,0,327,0,0,674409,0,88757,0,0
2,20240423,KRX,XGT01P,KRX BBIG 지수,1678.93,1690.71,1656.34,1656.34,-41.53,-2.45,...,399,0,5253,0,0,70825,0,897442,0,0